version: '3.8'

services:
  autonumbergame:
    image: autonumbergame:latest
    container_name: autonumbergame
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GAME_DATA_FILE=/app/data/game_data.json
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Дополнительный сервис для разработки
  autonumbergame-dev:
    build: .
    container_name: autonumbergame-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GAME_DATA_FILE=/app/data/game_data.json
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
